using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CircleSharp.Enumerations
{
	internal enum SpellDefinitions : int
	{
		SpellUndefined = -1,
		SpellReserved,

		SpellArmor,
		SpellTeleport,
		SpellBless,
		SpellBlindness,
		SpellBurningHands,
		SpellCallLightning,
		SpellCharm,
		SpellChillTouch,
		SpellClone,
		SpellColorSpray,
		SpellControlWeather,
		SpellCreateFood,
		SpellCreateWater,
		SpellCureBlind,
		SpellCureCritic,
		SpellCureLight,
		SpellCurse,
		SpellDetectAlign,
		SpellDetectInvisible,
		SpellDetectMagic,
		SpellDetectPoison,
		SpellDispelEvil,
		SpellEarthquake,
		SpellEnchantWeapon,
		SpellEnergyDrain,
		SpellFireball,
		SpellHarm,
		SpellHeal,
		SpellInvisible,
		SpellLightningBolt,
		SpellLocateObject,
		SpellMagicMissile,
		SpellPoison,
		SpellProtectFromEvil,
		SpellRemoveCurse,
		SpellSanctuary,
		SpellShockingGrasp,
		SpellSleep,
		SpellStrength,
		SpellSummon,
		SpellVentriloquate,
		SpellWordOfRecall,
		SpellRemovePoison,
		SpellSenseLife,
		SpellAnimateDead,
		SpellDispelGood,
		SpellGroupArmor,
		SpellGroupHeal,
		SpellGroupRecall,
		SpellInfravision,
		SpellWaterwalk,

		SpellIndex,

		SkillBackstab,
		SkillBash,
		SkillHide,
		SkillKick,
		SkillPickLock,
		SkillRescue,
		SkillSneak,
		SkillSteal,
		SkillTrack,

		SkillIndex,

		SpellIdentify,
		SpellFireBreath,
		SpellGasBreath,
		SpellFrostBreath,
		SpellAcidBreath,
		SpellLightningBreath,
		SpellAffect,

		TopSpellIndex,

		AttackHit,
		AttackString,
		AttackWhip,
		AttackSlash,
		AttackBite,
		AttackBludgeon,
		AttackCrush,
		AttackPound,
		AttackClaw,
		AttackMaul,
		AttackThrash,
		AttackPierce,
		AttackAttackBlast,
		AttackPunch,
		AttackStab,
		AttackSuffering,

		AttackIndex
	}
}
